name: Bundler and Export Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manifests:
        description: 'Enter the list of changed manifests (comma-separated)'
        required: true
        default: ''

jobs:
  # Step 1: Identify changed manifests
  identify-changes:
    runs-on: ubuntu-latest
    outputs:
      manifests: ${{ steps.changed.outputs.manifests }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'  # Pull submodules as well
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm ci

      - name: Identify changed manifests
        id: changed
        run: |
          if [ -z "${{ github.event.inputs.manifests }}" ]; then
            changed_manifests=$(npm run bundler -- list --changed)
            echo "Changed manifests: $changed_manifests"
          else
            changed_manifests="[${{ github.event.inputs.manifests }}]"
            echo "Using manually provided manifests: $changed_manifests"
          fi
          echo "manifests=$changed_manifests" >> $GITHUB_OUTPUT

  # Step 2: Spin up jobs for each changed manifest
  bundle-manifests:
    needs: identify-changes
    runs-on: ubuntu-latest
    if: ${{ needs.identify-changes.outputs.manifests != '[]' }}

    strategy:
      matrix:
        manifest: ${{ fromJson(needs.identify-changes.outputs.manifests) }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'  # Pull submodules as well (TODO: Only pull relevant submodules)

      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm ci

      - name: Run bundler to create export for manifest
        run: |
          npm run bundler -- bundle ${{ matrix.manifest }} --output export --source https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.repository }}/export

      - name: Commit export files to the export branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin export || git checkout --orphan export  # Create export branch if not exists
          cp -r export/* .
          git add .
          git commit -m "Add bundled files for ${matrix.manifest}"
          git push origin export --force

  # Step 3: Consolidate export files and flatten the export branch
  consolidate-export:
    needs: bundle-manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository and export branch in a separate worktree
        run: |
          git fetch origin main
          git checkout main
          git fetch origin export || git checkout --orphan export  # Create export branch if it doesn't exist
          git worktree add ./export export  # Add export branch in a separate directory

      - uses: actions/checkout@v2
      - name: Checkout export branch in a separate worktree
        run: |
          git fetch origin export || git checkout --orphan export  # Create export branch if it doesn't exist
          git worktree add ./export export  # Add export branch in a separate directory

      - name: Download export contents
        run: |
          cd export
          git pull origin export

      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm ci

      - name: Run bundler to finalize export
        run: |
          npm run bundler -- registry --output export

      - name: Commit export files to the export branch
        run: |
          cd export
          git add .
          git commit -m "Finalize package registry"
          git push origin export

